version: '3.9'
services:
  db:
    image: xbgmsharp/timescaledb-postgis
    container_name: db
    restart: unless-stopped
    env_file: .env
    environment:
      - POSTGRES_DB=postgres
      - TIMESCALEDB_TELEMETRY=off
      - PGDATA=/var/lib/postgresql/data/pgdata
      - TZ=UTC
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
      - $PWD/initdb:/docker-entrypoint-initdb.d
    logging:
      options:
        max-size: 10m

  api:
    image: postgrest/postgrest
    container_name: api
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file: .env
    environment:
      PGRST_DB_SCHEMA: api
      PGRST_DB_ANON_ROLE: api_anonymous
      PGRST_OPENAPI_SERVER_PROXY_URI: http://127.0.0.1:3000
      PGRST_DB_PRE_REQUEST: public.check_jwt
    network_mode: "host"
    depends_on:
      - db
    logging:
      options:
        max-size: 10m

  app:
    image: grafana/grafana:latest
    container_name: app
    restart: unless-stopped
    volumes:
      - data:/var/lib/grafana
      - data:/var/log/grafana
      - $PWD/grafana:/etc/grafana
    ports:
      - "3001:3000"
    network_mode: "host"
    env_file: .env
    environment:
      - GF_INSTALL_PLUGINS=pr0ps-trackmap-panel,fatcloud-windrose-panel
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SMTP_ENABLED=false
    depends_on:
      - db
    logging:
      options:
        max-size: 10m

volumes:
  data: {}
